path = "/var/lib/rspamd/dkim/$domain.$selector.key";
selector = "mail";
sign_authenticated = true;
use_domain = "header";
check_pubkey = true;
domain {
  km0digital.com {
    path = "/var/lib/rspamd/dkim/km0digital.com.mail.key";
    selector = "mail";
  }
}
